server:
  port: 8081
  servlet:
    context-path: /koko
spring:
  devtools:
      restart:
        enabled: true
  datasource:
        url: jdbc:mysql://localhost:3306/koko?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  http:
      encoding:
        force: true
  boot:
    admin:
      client:
        prefer-ip: true
      url: http://localhost:8082

mybatis:
    type-aliases-package: com.koko.*.entity
    mapper-locations: classpath*:mapper/*.xml
    check-config-location: true

mapper:
    mappers:
        - com.koko.core.base.BaseMapper
        - tk.mybatis.mapper.common.Mapper
    not-empty: true
    identity: mysql


# PageHelperConfig 可以替代此方案
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

koko:
  uploadPath: ./file/upload
  isDayType: true

  imagePath: ./file/image

logging:
  file: ./logs/koko-log.log
  level:
    com.koko.mapper: debug

dataType: mysql